### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Eikosa** [alankan886/SuperMemo2#4]
```
>>> from supermemo2 import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python38\site-packages\supermemo2\__init__.py", line 1, in <module>
    from .api import first_review, modify
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python38\site-packages\supermemo2\api.py", line 3, in <module>
    from .model import SMTwo
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python38\site-packages\supermemo2\model.py", line 11, in <module>
    class SMTwo:
  File "C:\Users\USERNAME\AppData\Roaming\Python\Python38\site-packages\supermemo2\model.py", line 18, in SMTwo
    on_setattr=attr.setters.validate
AttributeError: module 'attr' has no attribute 'setters'
```

**Comment by alankan886** [comment]
Hi @Eikosa,

Thank you for pointing that out.

It looks like I forgot to specify the required version for attrs.

I'm guessing you have the package attrs pre-installed, and it has a version lower than 20.1.0. The attrs.setters feature is new in 20.1.0.

I will specify the attrs version in setup.py and in README. The former should make sure attrs is at least version 20.1.0 after installing supermemo2.

But if you don't want to wait, you can just upgrade your attrs version to at least 20.1.0.
